name: weather-dl-v2-license-dep
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geojson
  - cdsapi=0.5.1
  - ecmwf-api-client=1.6.3
  - pip=22.3
  - pip:
    - git+https://github.com/google/pyink
    - kubernetes
    - google-cloud-secret-manager
    - aiohttp
    - numpy
    - xarray
    - apache-beam[gcp]
    - firebase-admin
