# weather-dl-v2-license-dep Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: batch/v1
kind: Job
metadata:
  name: weather-dl-v2-license-dep
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: weather-dl-v2-license-dep
          image: XXXXXXX
          imagePullPolicy: Always
          args: []
          resources:
            requests:
              cpu: "1500m"                  # CPU: 1.5 vCPU
              memory: "2Gi"                 # RAM: 2 GiB
              ephemeral-storage: "10Gi"     # Storage: 10 GiB
          volumeMounts:
          - name: config-volume
            mountPath: ./config
          # The liveness and readiness checks returns ok for all probes.
          livenessProbe:
            exec:
              command:
              - echo
              - ready
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
              - echo
              - ready
            initialDelaySeconds: 60
            periodSeconds: 60
      volumes:
        - name: config-volume
          configMap:
            name: dl-v2-config