---
# weather-dl-v2-license-dep Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-dl-v2-license-dep
  labels:
    app: weather-dl-v2-license-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-dl-v2-license-dep
  template:
    metadata:
      labels:
        app: weather-dl-v2-license-dep
    spec:
      containers:
        - name: weather-dl-v2-license-dep
          image: XXXXXXX
          imagePullPolicy: Always
          args: []
          # resources:
          #   # You must specify requests for CPU to autoscale
          #   # based on CPU utilization
          #   requests:
          #     cpu: "250m"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: weather-dl-v2-license-dep
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: weather-dl-v2-license-dep
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weather-dl-v2-license-dep
---