name: weather-dl-v2-server
channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray
  - geojson
  - pip=22.3
  - google-cloud-sdk=410.0.0
  - pip:
    - fastapi[all]
    - python-multipart
    - numpy
    - apache-beam[gcp]
    - aiohttp
    - firebase-admin
    - gcloud
